# Build test binary (optimized)
$(TEST_BIN): $(TEST_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $< -L$(BUILD_DIR) -lgeobolt $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(DATABASE_TEST_BIN): $(DATABASE_TEST_SRC) $(TEST_SUPPORT_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $(DATABASE_TEST_SRC) $(TEST_SUPPORT_SRC) -L$(BUILD_DIR) -lgeobolt \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(STORAGE_TEST_BIN): $(STORAGE_TEST_SRC) $(TEST_SUPPORT_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) -I$(TEST_DIR) $(CFLAGS) $(CFLAGS_OPT) $(STORAGE_TEST_SRC) $(TEST_SUPPORT_SRC) -L$(BUILD_DIR) -lgeobolt \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(SERVER_TEST_BIN): $(SERVER_TEST_SRC) $(TEST_SUPPORT_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $(SERVER_TEST_SRC) $(TEST_SUPPORT_SRC) -L$(BUILD_DIR) -lgeobolt \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(DAEMON_BIN): $(DAEMON_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $(DAEMON_SRC) -L$(BUILD_DIR) -lgeobolt \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(DAEMON_TEST_BIN): $(DAEMON_TEST_SRC) $(TEST_SUPPORT_SRC) $(DAEMON_BIN) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $(DAEMON_TEST_SRC) $(TEST_SUPPORT_SRC) -L$(BUILD_DIR) -lgeobolt \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

# Build test binary (debug with sanitizers)
$(TEST_BIN_DEBUG): $(TEST_SRC) $(DEBUG_LIBRARY_OBJECTS)
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_DEBUG) $< $(DEBUG_LIBRARY_OBJECTS) \
		$(LDFLAGS) $(LDLIBS) $(THREAD_LIBS) -o $@

$(DATABASE_TEST_BIN_DEBUG): $(DATABASE_TEST_SRC) $(TEST_SUPPORT_SRC) $(DEBUG_LIBRARY_OBJECTS)
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_DEBUG) $(DATABASE_TEST_SRC) $(TEST_SUPPORT_SRC) $(DEBUG_LIBRARY_OBJECTS) \
		$(LDFLAGS) $(LDLIBS) $(THREAD_LIBS) -o $@

$(STORAGE_TEST_BIN_DEBUG): $(STORAGE_TEST_SRC) $(TEST_SUPPORT_SRC) $(DEBUG_LIBRARY_OBJECTS)
	$(CC) $(CPPFLAGS) -I$(TEST_DIR) $(CFLAGS) $(CFLAGS_DEBUG) $(STORAGE_TEST_SRC) $(TEST_SUPPORT_SRC) \
		$(DEBUG_LIBRARY_OBJECTS) $(LDFLAGS) $(LDLIBS) $(THREAD_LIBS) -o $@

$(SERVER_TEST_BIN_DEBUG): $(SERVER_TEST_SRC) $(TEST_SUPPORT_SRC) $(DEBUG_LIBRARY_OBJECTS)
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_DEBUG) $(SERVER_TEST_SRC) $(TEST_SUPPORT_SRC) $(DEBUG_LIBRARY_OBJECTS) \
		$(LDFLAGS) $(LDLIBS) $(THREAD_LIBS) -o $@

$(DAEMON_BIN_DEBUG): $(DAEMON_SRC) $(DEBUG_LIBRARY_OBJECTS)
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_DEBUG) $(DAEMON_SRC) $(DEBUG_LIBRARY_OBJECTS) \
		$(LDFLAGS) $(LDLIBS) $(THREAD_LIBS) -o $@

$(DAEMON_TEST_BIN_DEBUG): $(DAEMON_TEST_SRC) $(TEST_SUPPORT_SRC) $(DEBUG_LIBRARY_OBJECTS) $(DAEMON_BIN_DEBUG)
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_DEBUG) $(DAEMON_TEST_SRC) $(TEST_SUPPORT_SRC) $(DEBUG_LIBRARY_OBJECTS) \
		$(LDFLAGS) $(LDLIBS) $(THREAD_LIBS) -o $@

$(TEST_BIN_SCALAR): $(TEST_SRC) $(SCALAR_LIBRARY_OBJECTS) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) -DGEO_SIMD_FORCE_SCALAR $(CFLAGS) $(CFLAGS_OPT) $< $(SCALAR_LIBRARY_OBJECTS) \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(DATABASE_TEST_BIN_SCALAR): $(DATABASE_TEST_SRC) $(TEST_SUPPORT_SRC) $(SCALAR_LIBRARY_OBJECTS) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) -DGEO_SIMD_FORCE_SCALAR $(CFLAGS) $(CFLAGS_OPT) $(DATABASE_TEST_SRC) $(TEST_SUPPORT_SRC) \
		$(SCALAR_LIBRARY_OBJECTS) $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(STORAGE_TEST_BIN_SCALAR): $(STORAGE_TEST_SRC) $(TEST_SUPPORT_SRC) $(SCALAR_LIBRARY_OBJECTS) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) -I$(TEST_DIR) -DGEO_SIMD_FORCE_SCALAR $(CFLAGS) $(CFLAGS_OPT) $(STORAGE_TEST_SRC) $(TEST_SUPPORT_SRC) \
		$(SCALAR_LIBRARY_OBJECTS) $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(SERVER_TEST_BIN_SCALAR): $(SERVER_TEST_SRC) $(TEST_SUPPORT_SRC) $(SCALAR_LIBRARY_OBJECTS) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) -DGEO_SIMD_FORCE_SCALAR $(CFLAGS) $(CFLAGS_OPT) $(SERVER_TEST_SRC) $(TEST_SUPPORT_SRC) \
		$(SCALAR_LIBRARY_OBJECTS) \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(DAEMON_BIN_SCALAR): $(DAEMON_SRC) $(SCALAR_LIBRARY_OBJECTS) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) -DGEO_SIMD_FORCE_SCALAR $(CFLAGS) $(CFLAGS_OPT) $(DAEMON_SRC) $(SCALAR_LIBRARY_OBJECTS) \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(DAEMON_TEST_BIN_SCALAR): $(DAEMON_TEST_SRC) $(TEST_SUPPORT_SRC) $(SCALAR_LIBRARY_OBJECTS) $(DAEMON_BIN_SCALAR) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) -DGEO_SIMD_FORCE_SCALAR $(CFLAGS) $(CFLAGS_OPT) $(DAEMON_TEST_SRC) $(TEST_SUPPORT_SRC) \
		$(SCALAR_LIBRARY_OBJECTS) $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

# Build the public-API sample
$(SAMPLE_BIN): $(SAMPLE_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $< -L$(BUILD_DIR) -lgeobolt $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(CLIENT_SAMPLE_BIN): $(CLIENT_SAMPLE_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $< -L$(BUILD_DIR) -lgeobolt $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(METADATA_SAMPLE_BIN): $(METADATA_SAMPLE_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $< -L$(BUILD_DIR) -lgeobolt $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

# Build demo benchmark
$(DEMO_BIN): $(DEMO_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $< -L$(BUILD_DIR) -lgeobolt $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(TOMBSTONE_BENCH_BIN): $(TOMBSTONE_BENCH_SRC) $(BENCHMARK_DIR)/benchmark_common.h $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(BENCHMARK_CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $< -L$(BUILD_DIR) -lgeobolt \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(STREAM_BENCH_BIN): $(STREAM_BENCH_SRC) $(BENCHMARK_DIR)/benchmark_common.h $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(BENCHMARK_CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $< -L$(BUILD_DIR) -lgeobolt \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(COMPACTION_BENCH_BIN): $(COMPACTION_BENCH_SRC) $(BENCHMARK_DIR)/benchmark_common.h $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(BENCHMARK_CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $< -L$(BUILD_DIR) -lgeobolt \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(SERVER_BENCH_BIN): $(SERVER_BENCH_SRC) $(BENCHMARK_DIR)/benchmark_common.h $(TEST_SUPPORT_SRC) $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) -I$(TEST_DIR) $(BENCHMARK_CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $(SERVER_BENCH_SRC) $(TEST_SUPPORT_SRC) \
		-L$(BUILD_DIR) -lgeobolt $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(QUERY_PLANNER_BENCH_BIN): $(QUERY_PLANNER_BENCH_SRC) $(BENCHMARK_DIR)/benchmark_common.h $(TEST_SUPPORT_SRC) \
		$(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) -I$(TEST_DIR) $(BENCHMARK_CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $(QUERY_PLANNER_BENCH_SRC) \
		$(TEST_SUPPORT_SRC) -L$(BUILD_DIR) -lgeobolt $(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@

$(SOAK_BIN): $(SOAK_SRC) $(BENCHMARK_DIR)/benchmark_common.h $(LIB_STATIC) FORCE_OPT_LINK
	$(CC) $(CPPFLAGS) $(BENCHMARK_CPPFLAGS) $(CFLAGS) $(CFLAGS_OPT) $< -L$(BUILD_DIR) -lgeobolt \
		$(LDFLAGS) $(OPT_LDLIBS) $(THREAD_LIBS) -o $@
